#==================================================================================================
# Xcodegen documentation
# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-scheme
#==================================================================================================

#==================================================================================================
name: XPFinanceUI
#==================================================================================================

settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "13.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "11.0"

configs:
  Debug: debug
  Release: release

#==================================================================================================
targets:
#==================================================================================================

#____________________________________________________________
# XPFinanceUI

  XPFinanceUI:

    platform: iOS
    type: framework

    sources:
      - path: XPFinanceUI

    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PRODUCT_BUNDLE_IDENTIFIER: br.com.minhacarteira.XPFinanceUI
      INFOPLIST_FILE: XPFinanceUI/Info.plist

      ENABLE_BITCODE: "YES"
      TARGETED_DEVICE_FAMILY: "1"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

    preBuildScripts:
      - script: "${PODS_ROOT}/SwiftGen/bin/swiftgen"
        name: SwiftGen
        
    postBuildScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
        name: SwiftLint      

#____________________________________________________________
# Tests

  XPFinanceUITests:

    platform: iOS
    type: bundle.unit-test
    
    sources:
      - path: XPFinanceUITests
        excludes:
          - "**/__Snapshots__"
    
    dependencies:
      - target: XPFinanceUI

#==================================================================================================
schemes:
#==================================================================================================

  FinanceUI:
    build:
      targets:
        XPFinanceUI: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - XPFinanceUI
      targets:
        - XPFinanceUITests

#==================================================================================================
