# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for challenge
  pod 'SwiftLint'
  pod 'API', :path => '../API'

  target 'challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
