name: challenge
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  challenge:
    platform: iOS
    type: application
    deploymentTarget: "17.0"
    sources: [challenge]

    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PRODUCT_BUNDLE_IDENTIFIER: br.com.wagnersales.challenge
      INFOPLIST_FILE: challenge/Info.plist

    postBuildScripts:
      - script: ${PODS_ROOT}/SwiftLint/swiftlint
        name: SwiftLint

  challengeTests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: challengeTests

    dependencies:
      - target: challenge

schemes:
  challenge:
    build:
      targets:
        challenge: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - challenge
      targets:
        - challengeTests
